import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
    Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions,
    DialogContent, DialogTitle, FormControl, Grid, InputLabel, LinearProgress, MenuItem,
    Paper, Select, Stack, Tab, Tabs, TextField, Typography,
} from '@mui/material';
import {
    Add, AssignmentLate, AttachFile, FactCheck, Gavel, Policy, Refresh, ReportProblem,
    TaskAlt, VerifiedUser,
} from '@mui/icons-material';
import { toast } from 'react-toastify';
import { useAuth } from '../contexts/AuthContext';
import { apiRequest } from '../utils/auth';
import {
    ComplianceEvent, ComplianceOptions, ComplianceRecordKind, ComplianceRegister, ComplianceSummary,
    ComplianceTab, CorrectiveAction, Inspection, NonConformity, Obligation, Permit, Regulation,
} from '../utils/compliance';

const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateLabel = (value: string) => new Date(value).toLocaleDateString();
const color = (status: string) => ['COMPLIANT', 'COMPLETED', 'ACTIVE', 'CLOSED'].includes(status) ? 'success' : ['NON_COMPLIANT', 'EXPIRED', 'CRITICAL', 'REVOKED'].includes(status) ? 'error' : ['OVERDUE', 'EXPIRING', 'ESCALATED', 'HIGH'].includes(status) ? 'warning' : 'default';
const emptyRegister: ComplianceRegister = { regulations: [], obligations: [], permits: [], inspections: [], nonConformities: [], events: [] };
const emptySummary: ComplianceSummary = { activeRegulations: 0, totalObligations: 0, compliantObligations: 0, overdueObligations: 0, expiringPermits: 0, scheduledInspections: 0, openNonConformities: 0, overdueActions: 0, complianceScore: 0 };
const initialForm = {
    code: '', reference: '', title: '', type: 'REGULATION', jurisdiction: '', regulator: '', description: '', effectiveDate: '', reviewDate: '', status: '',
    regulationId: '', projectId: '', requirement: '', department: '', responsibleOfficerId: '', dueDate: '', frequency: '', weight: '1',
    permitNumber: '', permitType: '', issuingAuthority: '', holder: '', issueDate: '', expiryDate: '', renewalLeadDays: '90', conditions: '',
    inspector: '', location: '', scheduledDate: '', detectedAt: '', obligationId: '', inspectionId: '', severity: 'MEDIUM', rootCause: '',
};
const initialEvidence = { kind: 'obligationId', recordId: '', name: '', url: '', mimeType: 'application/pdf', notes: '' };

const Compliance: React.FC = () => {
    const { user } = useAuth();
    const [register, setRegister] = useState(emptyRegister);
    const [summary, setSummary] = useState(emptySummary);
    const [options, setOptions] = useState<ComplianceOptions>({ users: [], projects: [], regulations: [], obligations: [], inspections: [], nonConformities: [] });
    const [loading, setLoading] = useState(true);
    const [tab, setTab] = useState<ComplianceTab>('regulations');
    const [search, setSearch] = useState('');
    const [createKind, setCreateKind] = useState<ComplianceRecordKind | null>(null);
    const [form, setForm] = useState(initialForm);
    const [parentFindingId, setParentFindingId] = useState('');
    const [evidenceOpen, setEvidenceOpen] = useState(false);
    const [evidence, setEvidence] = useState(initialEvidence);
    const [saving, setSaving] = useState(false);

    const manager = Boolean(user && ['ADMINISTRATOR', 'COMPLIANCE_OFFICER'].includes(user.role));
    const contributor = Boolean(user && ['ADMINISTRATOR', 'COMPLIANCE_OFFICER', 'DEPARTMENT_HEAD', 'PROJECT_MANAGER'].includes(user.role));

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const [registerResult, overviewResult, optionResult] = await Promise.all([
                apiRequest<ComplianceRegister>('/api/compliance/register'),
                apiRequest<{ summary: ComplianceSummary }>('/api/compliance/overview'),
                apiRequest<ComplianceOptions>('/api/compliance/options'),
            ]);
            setRegister(registerResult); setSummary(overviewResult.summary); setOptions(optionResult);
        } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not load compliance register'); }
        finally { setLoading(false); }
    }, []);
    useEffect(() => { void load(); }, [load]);

    const mutate = async (path: string, request: RequestInit, success: string) => {
        setSaving(true);
        try { await apiRequest(path, request); await load(); toast.success(success); return true; }
        catch (error) { toast.error(error instanceof Error ? error.message : 'Compliance operation failed'); return false; }
        finally { setSaving(false); }
    };

    const openCreate = (kind: ComplianceRecordKind, findingId = '') => { setCreateKind(kind); setParentFindingId(findingId); setForm(initialForm); };
    const create = async () => {
        if (!createKind) return;
        let path = `/${createKind}`;
        let body: Record<string, unknown> = {};
        if (createKind === 'regulations') body = { code: form.code, title: form.title, type: form.type, jurisdiction: form.jurisdiction, regulator: form.regulator, description: form.description, effectiveDate: form.effectiveDate, reviewDate: form.reviewDate || null, status: 'ACTIVE' };
        if (createKind === 'obligations') body = { regulationId: form.regulationId, projectId: form.projectId || null, reference: form.reference, title: form.title, requirement: form.requirement, department: form.department, responsibleOfficerId: form.responsibleOfficerId, dueDate: form.dueDate, frequency: form.frequency || null, weight: Number(form.weight) };
        if (createKind === 'permits') body = { regulationId: form.regulationId || null, projectId: form.projectId || null, permitNumber: form.permitNumber, title: form.title, permitType: form.permitType, issuingAuthority: form.issuingAuthority, holder: form.holder, issueDate: form.issueDate, expiryDate: form.expiryDate, status: 'ACTIVE', renewalLeadDays: Number(form.renewalLeadDays), conditions: form.conditions || null, responsibleOfficerId: form.responsibleOfficerId };
        if (createKind === 'inspections') body = { regulationId: form.regulationId || null, projectId: form.projectId || null, reference: form.reference, title: form.title, inspector: form.inspector, location: form.location, scheduledDate: form.scheduledDate, responsibleOfficerId: form.responsibleOfficerId };
        if (createKind === 'findings') { path = '/non-conformities'; body = { obligationId: form.obligationId || null, inspectionId: form.inspectionId || null, projectId: form.projectId || null, reference: form.reference, title: form.title, description: form.description, severity: form.severity, detectedAt: form.detectedAt, dueDate: form.dueDate, responsibleOfficerId: form.responsibleOfficerId, rootCause: form.rootCause || null }; }
        if (createKind === 'actions') { path = `/non-conformities/${parentFindingId}/actions`; body = { title: form.title, description: form.description, responsibleOfficerId: form.responsibleOfficerId, dueDate: form.dueDate }; }
        const success = await mutate(`/api/compliance${path}`, { method: 'POST', body: JSON.stringify(body) }, `${label(createKind)} record created`);
        if (success) { setCreateKind(null); setParentFindingId(''); }
    };
    const attachEvidence = async () => {
        const success = await mutate('/api/compliance/evidence', { method: 'POST', body: JSON.stringify({ [evidence.kind]: evidence.recordId, name: evidence.name, url: evidence.url, mimeType: evidence.mimeType || null, notes: evidence.notes || null }) }, 'Compliance evidence attached');
        if (success) { setEvidenceOpen(false); setEvidence(initialEvidence); }
    };
    const recordAction = (path: string, body: Record<string, unknown>, success: string) => mutate(`/api/compliance${path}`, { method: 'POST', body: JSON.stringify(body) }, success);
    const patchRecord = (path: string, body: Record<string, unknown>, success: string) => mutate(`/api/compliance${path}`, { method: 'PATCH', body: JSON.stringify(body) }, success);

    const counts = [
        ['Compliance score', `${summary.complianceScore}%`, <VerifiedUser />], ['Active regulations', summary.activeRegulations, <Gavel />],
        ['Overdue obligations', summary.overdueObligations, <AssignmentLate />], ['Expiring permits', summary.expiringPermits, <Policy />],
        ['Scheduled inspections', summary.scheduledInspections, <FactCheck />], ['Open findings', summary.openNonConformities, <ReportProblem />],
    ] as const;
    const query = search.trim().toLowerCase();
    const matches = (...values: unknown[]) => !query || values.some((value) => String(value || '').toLowerCase().includes(query));

    return <Box sx={{ width: '100%' }}>
        <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2} sx={{ mb: 3 }}><Box><Typography variant="h4" color="primary" fontWeight={800}>Compliance & Regulation</Typography><Typography color="text.secondary">Control oil-sector obligations, permits, inspections, evidence, findings, corrective action, and escalation.</Typography></Box><Stack direction="row" gap={1}><Button startIcon={<Refresh />} onClick={() => void load()}>Refresh</Button><Button component="a" href="/api/compliance/reports/register.csv" target="_blank" variant="outlined">Export Register</Button>{contributor && <Button startIcon={<AttachFile />} onClick={() => setEvidenceOpen(true)}>Evidence</Button>}</Stack></Stack>
        <Grid container spacing={1.5} sx={{ mb: 2 }}>{counts.map(([name, value, icon]) => <Grid item xs={6} md={4} lg={2} key={name}><Paper variant="outlined" sx={{ p: 1.5, height: '100%' }}><Stack direction="row" gap={1}>{icon}<Box><Typography variant="caption" color="text.secondary">{name}</Typography><Typography variant="h6" fontWeight={800}>{value}</Typography></Box></Stack></Paper></Grid>)}</Grid>
        <Card variant="outlined"><CardContent><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={1}><Tabs value={tab} onChange={(_event, value: ComplianceTab) => setTab(value)} variant="scrollable"><Tab value="regulations" label={`Regulations (${register.regulations.length})`} /><Tab value="obligations" label={`Obligations (${register.obligations.length})`} /><Tab value="permits" label={`Permits (${register.permits.length})`} /><Tab value="inspections" label={`Inspections (${register.inspections.length})`} /><Tab value="findings" label={`Findings (${register.nonConformities.length})`} /><Tab value="workflow" label="Audit trail" /></Tabs>{tab !== 'workflow' && ((manager && ['regulations', 'permits', 'inspections'].includes(tab)) || (contributor && ['obligations', 'findings'].includes(tab))) && <Button startIcon={<Add />} variant="contained" onClick={() => openCreate(tab)}>Add {label(tab.slice(0, -1))}</Button>}</Stack>
            <TextField value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search the selected compliance register" fullWidth size="small" sx={{ my: 2 }} />
            {loading ? <Box sx={{ minHeight: 260, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box> : <>
                {tab === 'regulations' && <Regulations rows={register.regulations.filter((item) => matches(item.code, item.title, item.regulator, item.jurisdiction))} />}
                {tab === 'obligations' && <Obligations rows={register.obligations.filter((item) => matches(item.reference, item.title, item.department, item.responsibleOfficer.name))} manager={manager} verify={(id) => void patchRecord(`/obligations/${id}`, { status: 'COMPLIANT', verificationComment: 'Verified through compliance workspace' }, 'Obligation verified')} />}
                {tab === 'permits' && <Permits rows={register.permits.filter((item) => matches(item.permitNumber, item.title, item.issuingAuthority, item.holder))} />}
                {tab === 'inspections' && <Inspections rows={register.inspections.filter((item) => matches(item.reference, item.title, item.inspector, item.location))} manager={manager} complete={(id) => void patchRecord(`/inspections/${id}`, { status: 'COMPLETED', outcome: 'COMPLIANT', score: 100, completedDate: new Date().toISOString() }, 'Inspection completed')} />}
                {tab === 'findings' && <Findings rows={register.nonConformities.filter((item) => matches(item.reference, item.title, item.severity, item.responsibleOfficer.name))} manager={manager} contributor={contributor} addAction={(id) => openCreate('actions', id)} escalate={(id) => void recordAction(`/non-conformities/${id}/escalate`, { level: 'DEPARTMENT_HEAD', comment: 'Escalated from compliance workspace' }, 'Finding escalated')} close={(id) => void patchRecord(`/non-conformities/${id}`, { status: 'CLOSED' }, 'Finding closed')} completeAction={(id) => void patchRecord(`/corrective-actions/${id}`, { status: 'COMPLETED', progress: 100 }, 'Corrective action verified')} />}
                {tab === 'workflow' && <Workflow rows={register.events.filter((item) => matches(item.entityType, item.action, item.actor.name, item.comment))} />}
            </>}
        </CardContent></Card>
        <CreateDialog kind={createKind} form={form} setForm={setForm} options={options} close={() => setCreateKind(null)} save={() => void create()} saving={saving} />
        <EvidenceDialog open={evidenceOpen} form={evidence} setForm={setEvidence} options={options} register={register} close={() => setEvidenceOpen(false)} save={() => void attachEvidence()} saving={saving} />
    </Box>;
};

const Empty = ({ text }: { text: string }) => <Alert severity="info">{text}</Alert>;
const RecordCard: React.FC<{ title: string; subtitle: string; status: string; children?: React.ReactNode; actions?: React.ReactNode }> = ({ title, subtitle, status, children, actions }) => <Paper variant="outlined" sx={{ p: 1.5, mb: 1.25 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={1}><Box><Stack direction="row" gap={1} alignItems="center"><Typography fontWeight={800}>{title}</Typography><Chip size="small" color={color(status)} label={label(status)} /></Stack><Typography variant="body2" color="text.secondary">{subtitle}</Typography>{children}</Box>{actions && <Stack direction="row" gap={1} alignItems="center">{actions}</Stack>}</Stack></Paper>;
const Regulations = ({ rows }: { rows: Regulation[] }) => rows.length ? <>{rows.map((item) => <RecordCard key={item.id} title={`${item.code} · ${item.title}`} subtitle={`${label(item.type)} · ${item.regulator} · ${item.jurisdiction}`} status={item.status}><Typography variant="body2" sx={{ mt: 0.75 }}>{item.description}</Typography><Typography variant="caption" color="text.secondary">{item.status === 'DRAFT' ? 'Recorded' : 'Effective'} {dateLabel(item.effectiveDate)}{item.reviewDate ? ` · Review ${dateLabel(item.reviewDate)}` : ''}</Typography></RecordCard>)}</> : <Empty text="No regulations match this search." />;
const Obligations = ({ rows, manager, verify }: { rows: Obligation[]; manager: boolean; verify: (id: string) => void }) => rows.length ? <>{rows.map((item) => <RecordCard key={item.id} title={`${item.reference} · ${item.title}`} subtitle={`${item.regulation.code} · ${item.department} · ${item.responsibleOfficer.name}`} status={item.effectiveStatus} actions={manager && item.effectiveStatus !== 'COMPLIANT' ? <Button size="small" color="success" onClick={() => verify(item.id)}>Verify</Button> : undefined}><Typography variant="caption">Due {dateLabel(item.dueDate)} · Weight {item.weight} · Score {item.score}%</Typography><LinearProgress variant="determinate" value={item.score} sx={{ mt: .75, height: 6, borderRadius: 3 }} /></RecordCard>)}</> : <Empty text="No obligations match this search." />;
const Permits = ({ rows }: { rows: Permit[] }) => rows.length ? <>{rows.map((item) => <RecordCard key={item.id} title={`${item.permitNumber} · ${item.title}`} subtitle={`${item.permitType} · ${item.issuingAuthority} · ${item.holder}`} status={item.effectiveStatus}><Typography variant="caption">Issued {dateLabel(item.issueDate)} · Expires {dateLabel(item.expiryDate)} · Officer {item.responsibleOfficer.name}</Typography></RecordCard>)}</> : <Empty text="No permits match this search." />;
const Inspections = ({ rows, manager, complete }: { rows: Inspection[]; manager: boolean; complete: (id: string) => void }) => rows.length ? <>{rows.map((item) => <RecordCard key={item.id} title={`${item.reference} · ${item.title}`} subtitle={`${item.inspector} · ${item.location} · ${item.responsibleOfficer.name}`} status={item.status} actions={manager && item.status !== 'COMPLETED' ? <Button size="small" onClick={() => complete(item.id)}>Complete</Button> : undefined}><Typography variant="caption">Scheduled {dateLabel(item.scheduledDate)} · Outcome {label(item.outcome)}{item.score != null ? ` · Score ${item.score}%` : ''}</Typography></RecordCard>)}</> : <Empty text="No inspections match this search." />;
const Findings = ({ rows, manager, contributor, addAction, escalate, close, completeAction }: { rows: NonConformity[]; manager: boolean; contributor: boolean; addAction: (id: string) => void; escalate: (id: string) => void; close: (id: string) => void; completeAction: (id: string) => void }) => rows.length ? <>{rows.map((item) => <RecordCard key={item.id} title={`${item.reference} · ${item.title}`} subtitle={`${label(item.severity)} severity · ${item.responsibleOfficer.name} · Due ${dateLabel(item.dueDate)}`} status={item.status} actions={<>{contributor && item.status !== 'CLOSED' && <Button size="small" onClick={() => addAction(item.id)}>Action</Button>}{manager && !['CLOSED', 'ESCALATED'].includes(item.status) && <Button size="small" color="warning" onClick={() => escalate(item.id)}>Escalate</Button>}{manager && item.status !== 'CLOSED' && <Button size="small" color="success" onClick={() => close(item.id)}>Close</Button>}</>}><Typography variant="body2" sx={{ mt: .5 }}>{item.description}</Typography>{item.escalationLevel !== 'NONE' && <Typography variant="caption" color="warning.main">Escalation: {label(item.escalationLevel)}</Typography>}{item.correctiveActions.map((action: CorrectiveAction) => <Paper key={action.id} variant="outlined" sx={{ p: 1, mt: 1 }}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="body2" fontWeight={700}>{action.title}</Typography><Typography variant="caption">{action.responsibleOfficer.name} · Due {dateLabel(action.dueDate)} · {action.progress}%</Typography></Box><Stack direction="row" gap={1}><Chip size="small" label={label(action.status)} />{manager && action.status !== 'COMPLETED' && <Button size="small" onClick={() => completeAction(action.id)}>Verify</Button>}</Stack></Stack></Paper>)}</RecordCard>)}</> : <Empty text="No non-conformities match this search." />;
const Workflow = ({ rows }: { rows: ComplianceEvent[] }) => rows.length ? <Stack spacing={1}>{rows.map((item) => <Paper key={item.id} variant="outlined" sx={{ p: 1.25 }}><Typography fontWeight={700}>{label(item.action)} · {label(item.entityType)}</Typography><Typography variant="caption" color="text.secondary">{item.actor.name} · {new Date(item.createdAt).toLocaleString()}{item.fromStatus || item.toStatus ? ` · ${label(item.fromStatus || 'new')} → ${label(item.toStatus || '')}` : ''}{item.comment ? ` · ${item.comment}` : ''}</Typography></Paper>)}</Stack> : <Empty text="No workflow events match this search." />;

const CreateDialog: React.FC<{ kind: ComplianceRecordKind | null; form: typeof initialForm; setForm: React.Dispatch<React.SetStateAction<typeof initialForm>>; options: ComplianceOptions; close: () => void; save: () => void; saving: boolean }> = ({ kind, form, setForm, options, close, save, saving }) => {
    if (!kind) return null;
    const set = (key: keyof typeof initialForm) => (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value });
    const select = (key: keyof typeof initialForm) => (event: { target: { value: unknown } }) => setForm({ ...form, [key]: String(event.target.value) });
    const owners = options.users;
    return <Dialog open onClose={close} fullWidth maxWidth="md"><DialogTitle>Add {label(kind === 'actions' ? 'corrective action' : kind.slice(0, -1))}</DialogTitle><DialogContent><Grid container spacing={2} sx={{ mt: .25 }}>
        {kind === 'regulations' && <><Grid item xs={12} md={4}><TextField label="Regulation code" value={form.code} onChange={set('code')} fullWidth required /></Grid><Grid item xs={12} md={8}><TextField label="Title" value={form.title} onChange={set('title')} fullWidth required /></Grid><Grid item xs={12} md={4}><FormControl fullWidth><InputLabel>Type</InputLabel><Select value={form.type} label="Type" onChange={select('type')}>{['LAW', 'REGULATION', 'POLICY', 'STANDARD', 'GUIDELINE', 'LICENCE_REQUIREMENT'].map((value) => <MenuItem key={value} value={value}>{label(value)}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={4}><TextField label="Jurisdiction" value={form.jurisdiction} onChange={set('jurisdiction')} fullWidth required /></Grid><Grid item xs={12} md={4}><TextField label="Regulator" value={form.regulator} onChange={set('regulator')} fullWidth required /></Grid><Grid item xs={12}><TextField label="Description" value={form.description} onChange={set('description')} multiline minRows={3} fullWidth required /></Grid><Grid item xs={12} md={6}><TextField type="date" label="Effective date" InputLabelProps={{ shrink: true }} value={form.effectiveDate} onChange={set('effectiveDate')} fullWidth required /></Grid><Grid item xs={12} md={6}><TextField type="date" label="Review date" InputLabelProps={{ shrink: true }} value={form.reviewDate} onChange={set('reviewDate')} fullWidth /></Grid></>}
        {kind === 'obligations' && <><SelectField labelText="Regulation" value={form.regulationId} onChange={select('regulationId')} items={options.regulations.map((item) => ({ value: item.id, text: `${item.code} · ${item.title}` }))} /><CommonReference form={form} set={set} /><Grid item xs={12}><TextField label="Requirement" value={form.requirement} onChange={set('requirement')} multiline minRows={3} fullWidth required /></Grid><Grid item xs={12} md={6}><TextField label="Department" value={form.department} onChange={set('department')} fullWidth required /></Grid><Grid item xs={12} md={3}><TextField label="Frequency" value={form.frequency} onChange={set('frequency')} fullWidth /></Grid><Grid item xs={12} md={3}><TextField type="number" label="Weight" value={form.weight} onChange={set('weight')} fullWidth /></Grid><OwnerAndProject form={form} select={select} options={options} /><Grid item xs={12} md={6}><DateField labelText="Due date" value={form.dueDate} change={set('dueDate')} /></Grid></>}
        {kind === 'permits' && <><Grid item xs={12} md={4}><TextField label="Permit number" value={form.permitNumber} onChange={set('permitNumber')} fullWidth required /></Grid><Grid item xs={12} md={8}><TextField label="Title" value={form.title} onChange={set('title')} fullWidth required /></Grid><Grid item xs={12} md={4}><TextField label="Permit type" value={form.permitType} onChange={set('permitType')} fullWidth required /></Grid><Grid item xs={12} md={4}><TextField label="Issuing authority" value={form.issuingAuthority} onChange={set('issuingAuthority')} fullWidth required /></Grid><Grid item xs={12} md={4}><TextField label="Holder" value={form.holder} onChange={set('holder')} fullWidth required /></Grid><SelectField labelText="Regulation (optional)" value={form.regulationId} onChange={select('regulationId')} optional items={options.regulations.map((item) => ({ value: item.id, text: `${item.code} · ${item.title}` }))} /><OwnerAndProject form={form} select={select} options={options} /><Grid item xs={12} md={4}><DateField labelText="Issue date" value={form.issueDate} change={set('issueDate')} /></Grid><Grid item xs={12} md={4}><DateField labelText="Expiry date" value={form.expiryDate} change={set('expiryDate')} /></Grid><Grid item xs={12} md={4}><TextField type="number" label="Renewal lead days" value={form.renewalLeadDays} onChange={set('renewalLeadDays')} fullWidth /></Grid><Grid item xs={12}><TextField label="Conditions" value={form.conditions} onChange={set('conditions')} multiline fullWidth /></Grid></>}
        {kind === 'inspections' && <><CommonReference form={form} set={set} /><Grid item xs={12} md={6}><TextField label="Inspector / organization" value={form.inspector} onChange={set('inspector')} fullWidth required /></Grid><Grid item xs={12} md={6}><TextField label="Location" value={form.location} onChange={set('location')} fullWidth required /></Grid><SelectField labelText="Regulation (optional)" value={form.regulationId} onChange={select('regulationId')} optional items={options.regulations.map((item) => ({ value: item.id, text: `${item.code} · ${item.title}` }))} /><OwnerAndProject form={form} select={select} options={options} /><Grid item xs={12} md={6}><DateField labelText="Scheduled date" value={form.scheduledDate} change={set('scheduledDate')} /></Grid></>}
        {kind === 'findings' && <><CommonReference form={form} set={set} /><Grid item xs={12}><TextField label="Description" value={form.description} onChange={set('description')} multiline minRows={3} fullWidth required /></Grid><SelectField labelText="Obligation (optional)" value={form.obligationId} onChange={select('obligationId')} optional items={options.obligations.map((item) => ({ value: item.id, text: `${item.reference} · ${item.title}` }))} /><SelectField labelText="Inspection (optional)" value={form.inspectionId} onChange={select('inspectionId')} optional items={options.inspections.map((item) => ({ value: item.id, text: `${item.reference} · ${item.title}` }))} /><OwnerAndProject form={form} select={select} options={options} /><SelectField labelText="Severity" value={form.severity} onChange={select('severity')} items={['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map((value) => ({ value, text: label(value) }))} /><Grid item xs={12} md={6}><DateField labelText="Detected date" value={form.detectedAt} change={set('detectedAt')} /></Grid><Grid item xs={12} md={6}><DateField labelText="Corrective due date" value={form.dueDate} change={set('dueDate')} /></Grid><Grid item xs={12}><TextField label="Root cause" value={form.rootCause} onChange={set('rootCause')} multiline fullWidth /></Grid></>}
        {kind === 'actions' && <><Grid item xs={12}><TextField label="Action title" value={form.title} onChange={set('title')} fullWidth required /></Grid><Grid item xs={12}><TextField label="Action description" value={form.description} onChange={set('description')} multiline minRows={3} fullWidth required /></Grid><SelectField labelText="Responsible officer" value={form.responsibleOfficerId} onChange={select('responsibleOfficerId')} items={owners.map((item) => ({ value: item.id, text: `${item.name} · ${item.email}` }))} /><Grid item xs={12} md={6}><DateField labelText="Due date" value={form.dueDate} change={set('dueDate')} /></Grid></>}
    </Grid></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>Create Record</Button></DialogActions></Dialog>;
};

const CommonReference = ({ form, set }: { form: typeof initialForm; set: (key: keyof typeof initialForm) => (event: React.ChangeEvent<HTMLInputElement>) => void }) => <><Grid item xs={12} md={4}><TextField label="Reference" value={form.reference} onChange={set('reference')} fullWidth required /></Grid><Grid item xs={12} md={8}><TextField label="Title" value={form.title} onChange={set('title')} fullWidth required /></Grid></>;
const DateField = ({ labelText, value, change }: { labelText: string; value: string; change: (event: React.ChangeEvent<HTMLInputElement>) => void }) => <TextField type="date" label={labelText} InputLabelProps={{ shrink: true }} value={value} onChange={change} fullWidth required />;
const SelectField = ({ labelText, value, onChange, items, optional }: { labelText: string; value: string; onChange: (event: { target: { value: unknown } }) => void; items: Array<{ value: string; text: string }>; optional?: boolean }) => <Grid item xs={12} md={6}><FormControl fullWidth required={!optional}><InputLabel>{labelText}</InputLabel><Select value={value} label={labelText} onChange={onChange}>{optional && <MenuItem value=""><em>Not linked</em></MenuItem>}{items.map((item) => <MenuItem key={item.value} value={item.value}>{item.text}</MenuItem>)}</Select></FormControl></Grid>;
const OwnerAndProject = ({ form, select, options }: { form: typeof initialForm; select: (key: keyof typeof initialForm) => (event: { target: { value: unknown } }) => void; options: ComplianceOptions }) => <><SelectField labelText="Responsible officer" value={form.responsibleOfficerId} onChange={select('responsibleOfficerId')} items={options.users.map((item) => ({ value: item.id, text: `${item.name} · ${item.email}` }))} /><SelectField labelText="Project (optional)" value={form.projectId} onChange={select('projectId')} optional items={options.projects.map((item) => ({ value: item.id, text: `${item.code} · ${item.title}` }))} /></>;

const EvidenceDialog: React.FC<{ open: boolean; form: typeof initialEvidence; setForm: React.Dispatch<React.SetStateAction<typeof initialEvidence>>; options: ComplianceOptions; register: ComplianceRegister; close: () => void; save: () => void; saving: boolean }> = ({ open, form, setForm, options, register, close, save, saving }) => {
    const records = form.kind === 'obligationId' ? options.obligations : form.kind === 'permitId' ? register.permits.map((item) => ({ id: item.id, reference: item.permitNumber, title: item.title })) : form.kind === 'inspectionId' ? options.inspections : form.kind === 'nonConformityId' ? options.nonConformities : register.nonConformities.flatMap((item) => item.correctiveActions.map((action) => ({ id: action.id, reference: item.reference, title: action.title })));
    return <Dialog open={open} onClose={close} fullWidth maxWidth="sm"><DialogTitle>Attach compliance evidence</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><FormControl fullWidth><InputLabel>Record type</InputLabel><Select value={form.kind} label="Record type" onChange={(event) => setForm({ ...form, kind: event.target.value, recordId: '' })}>{[['obligationId', 'Obligation'], ['permitId', 'Permit / licence'], ['inspectionId', 'Inspection'], ['nonConformityId', 'Non-conformity'], ['correctiveActionId', 'Corrective action']].map(([value, text]) => <MenuItem key={value} value={value}>{text}</MenuItem>)}</Select></FormControl><FormControl fullWidth required><InputLabel>Compliance record</InputLabel><Select value={form.recordId} label="Compliance record" onChange={(event) => setForm({ ...form, recordId: event.target.value })}>{records.map((item) => <MenuItem key={item.id} value={item.id}>{item.reference} · {item.title}</MenuItem>)}</Select></FormControl><TextField label="Evidence name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><TextField label="Secure HTTPS URL" type="url" value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} required helperText="Link to the approved evidence repository; files are not stored in local storage." /><TextField label="MIME type" value={form.mimeType} onChange={(event) => setForm({ ...form, mimeType: event.target.value })} /><TextField label="Notes" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} multiline /></Stack></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>Attach Evidence</Button></DialogActions></Dialog>;
};

export default Compliance;
