export type ComplianceTab = 'regulations' | 'obligations' | 'permits' | 'inspections' | 'findings' | 'workflow';
export type ComplianceRecordKind = Exclude<ComplianceTab, 'workflow'> | 'actions';
export interface ComplianceUser { id: string; name: string; email: string; role: string }
export interface ComplianceProject { id: string; title: string; code: string; department: string; managerId: string }
export interface ComplianceEvidence { id: string; name: string; url: string; mimeType: string | null; notes: string | null; uploadedBy: ComplianceUser; createdAt: string }
export interface Regulation { id: string; code: string; title: string; type: string; jurisdiction: string; regulator: string; description: string; effectiveDate: string; reviewDate: string | null; status: string }
export interface Obligation { id: string; regulationId: string; regulation: Regulation; project: ComplianceProject | null; reference: string; title: string; requirement: string; department: string; responsibleOfficerId: string; responsibleOfficer: ComplianceUser; dueDate: string; frequency: string | null; weight: number; status: string; effectiveStatus: string; score: number; verificationComment: string | null; evidence: ComplianceEvidence[] }
export interface Permit { id: string; regulation: Regulation | null; project: ComplianceProject | null; permitNumber: string; title: string; permitType: string; issuingAuthority: string; holder: string; issueDate: string; expiryDate: string; status: string; effectiveStatus: string; renewalLeadDays: number; conditions: string | null; responsibleOfficer: ComplianceUser; evidence: ComplianceEvidence[] }
export interface Inspection { id: string; regulation: Regulation | null; project: ComplianceProject | null; reference: string; title: string; inspector: string; location: string; scheduledDate: string; completedDate: string | null; status: string; outcome: string; score: number | null; notes: string | null; responsibleOfficer: ComplianceUser; evidence: ComplianceEvidence[] }
export interface CorrectiveAction { id: string; title: string; description: string; responsibleOfficerId: string; responsibleOfficer: ComplianceUser; dueDate: string; status: string; progress: number; completionNotes: string | null; evidence: ComplianceEvidence[] }
export interface NonConformity { id: string; obligation: { id: string; reference: string; title: string } | null; inspection: { id: string; reference: string; title: string } | null; project: ComplianceProject | null; reference: string; title: string; description: string; severity: string; status: string; detectedAt: string; dueDate: string; responsibleOfficerId: string; responsibleOfficer: ComplianceUser; rootCause: string | null; escalationLevel: string; correctiveActions: CorrectiveAction[]; evidence: ComplianceEvidence[] }
export interface ComplianceEvent { id: string; entityType: string; entityId: string; action: string; fromStatus: string | null; toStatus: string | null; comment: string | null; actor: ComplianceUser; createdAt: string }
export interface ComplianceSummary { activeRegulations: number; totalObligations: number; compliantObligations: number; overdueObligations: number; expiringPermits: number; scheduledInspections: number; openNonConformities: number; overdueActions: number; complianceScore: number }
export interface ComplianceRegister { regulations: Regulation[]; obligations: Obligation[]; permits: Permit[]; inspections: Inspection[]; nonConformities: NonConformity[]; events: ComplianceEvent[] }
export interface ComplianceOptions { users: ComplianceUser[]; projects: ComplianceProject[]; regulations: Array<Pick<Regulation, 'id' | 'code' | 'title'>>; obligations: Array<Pick<Obligation, 'id' | 'reference' | 'title'>>; inspections: Array<Pick<Inspection, 'id' | 'reference' | 'title'>>; nonConformities: Array<Pick<NonConformity, 'id' | 'reference' | 'title'>> }
