export type KpiTab = 'frameworks' | 'indicators' | 'periods' | 'workflow';
export type KpiCreateKind = 'framework' | 'result' | 'indicator' | 'period' | 'target' | 'measurement' | 'source';
export interface KpiUser { id: string; name: string; email: string; role: string }
export interface KpiProject { id: string; code: string; title: string; department: string; managerId: string }
export interface KpiEvidence { id: string; name: string; url: string; mimeType: string | null; notes: string | null; uploadedBy: KpiUser; createdAt: string }
export interface ResultLevel { id: string; frameworkId: string; parentId: string | null; code: string; type: string; title: string; description: string | null; sortOrder: number }
export interface KpiTarget { id: string; indicatorId: string; periodId: string; targetValue: string; notes: string | null; period: KpiPeriod }
export interface KpiMeasurement { id: string; indicatorId: string; periodId: string; actualValue: string; measuredAt: string; narrative: string | null; sourceType: string; sourceReference: string | null; status: string; createdById: string; createdBy: KpiUser; verifiedBy: KpiUser | null; verificationComment: string | null; evidence: KpiEvidence[] }
export interface KpiDataSource { id: string; indicatorId: string; name: string; sourceType: string; endpoint: string | null; valuePath: string | null; aggregation: string; isActive: boolean; lastSyncedAt: string | null; lastValue: string | null; lastError: string | null }
export interface KpiPerformance { actual: number | null; target: number; achievement: number | null; health: string }
export interface KpiIndicator { id: string; frameworkId: string; resultLevelId: string | null; resultLevel: ResultLevel | null; code: string; name: string; description: string; unit: string; dataType: string; direction: string; frequency: string; baselineValue: string; baselineDate: string; finalTargetValue: string; weight: number; tolerance: string; disaggregation: string[] | null; formula: string | null; sourceDescription: string | null; status: string; ownerId: string; owner: KpiUser; targets: KpiTarget[]; measurements: KpiMeasurement[]; dataSources: KpiDataSource[]; evidence: KpiEvidence[]; performance: KpiPerformance }
export interface KpiPeriod { id: string; frameworkId: string; name: string; startDate: string; endDate: string; dueDate: string; status: string; submittedBy: KpiUser | null; reviewedBy: KpiUser | null; reviewComment: string | null; targets: KpiTarget[]; measurements: KpiMeasurement[] }
export interface ResultsFramework { id: string; projectId: string; project: KpiProject; code: string; name: string; description: string | null; startDate: string; endDate: string; status: string; ownerId: string; owner: KpiUser; resultLevels: ResultLevel[]; indicators: KpiIndicator[]; periods: KpiPeriod[] }
export interface KpiEvent { id: string; entityType: string; entityId: string; action: string; fromStatus: string | null; toStatus: string | null; comment: string | null; actor: KpiUser; createdAt: string }
export interface KpiRegister { frameworks: ResultsFramework[]; events: KpiEvent[] }
export interface KpiSummary { frameworks: number; activeIndicators: number; openPeriods: number; overduePeriods: number; pendingVerification: number; reportingRate: number; portfolioScore: number; onTrack: number; atRisk: number; offTrack: number; notReported: number }
export interface KpiOptions { users: KpiUser[]; projects: KpiProject[]; frameworks: Array<Pick<ResultsFramework, 'id' | 'code' | 'name' | 'projectId' | 'ownerId'>>; indicators: Array<Pick<KpiIndicator, 'id' | 'code' | 'name' | 'frameworkId' | 'status'>>; periods: Array<Pick<KpiPeriod, 'id' | 'name' | 'frameworkId' | 'startDate' | 'endDate' | 'status'>> }
