export type SupplyChainTab = 'suppliers' | 'contracts' | 'requests' | 'deliveries' | 'reviews' | 'workflow';
export type SupplyRecordKind = Exclude<SupplyChainTab, 'workflow'> | 'qualification';
export interface SupplyUser { id: string; name: string; email: string; role: string }
export interface SupplyProject { id: string; code: string; title: string; department: string; managerId: string }
export interface SupplyEvidence { id: string; name: string; url: string; mimeType: string | null; notes: string | null; uploadedBy: SupplyUser; createdAt: string }
export interface SupplierQualification { id: string; reference: string; status: string; effectiveStatus: string; submittedAt: string | null; reviewedAt: string | null; expiresAt: string | null; technicalScore: number | null; financialScore: number | null; hseScore: number | null; localContentScore: number | null; overallScore: string | null; reviewer: SupplyUser | null; notes: string | null }
export interface SupplierReview { id: string; supplierId: string; supplier: Supplier; contract: SupplierContract | null; periodStart: string; periodEnd: string; qualityScore: number; deliveryScore: number; hseScore: number; localContentScore: number; costScore: number; overallScore: string; comments: string | null; reviewer: SupplyUser }
export interface Supplier { id: string; supplierCode: string; legalName: string; tradingName: string | null; registrationNumber: string | null; taxNumber: string | null; sector: string; categories: string[]; country: string; address: string | null; contactName: string; contactEmail: string; contactPhone: string | null; status: string; localContentPercentage: string; hseCertification: string | null; notes: string | null; createdBy: SupplyUser; qualifications: SupplierQualification[]; performanceReviews: SupplierReview[]; averagePerformance: number | null; evidence: SupplyEvidence[] }
export interface SupplierContract { id: string; supplierId: string; supplier: Supplier; project: SupplyProject | null; contractNumber: string; title: string; description: string | null; startDate: string; endDate: string; currency: string; value: string; status: string; effectiveStatus: string; renewalLeadDays: number; responsibleOfficer: SupplyUser; signedAt: string | null }
export interface PurchaseRequest { id: string; requestNumber: string; supplier: Supplier | null; contract: SupplierContract | null; project: SupplyProject | null; title: string; description: string; requiredBy: string; currency: string; estimatedAmount: string; status: string; createdBy: SupplyUser; reviewedBy: SupplyUser | null; reviewComment: string | null }
export interface SupplierDelivery { id: string; supplier: Supplier; contract: SupplierContract | null; purchaseRequest: PurchaseRequest | null; deliveryNumber: string; scheduledDate: string; actualDate: string | null; location: string; items: string; status: string; qualityScore: number | null; hseScore: number | null; acceptedBy: SupplyUser | null; acceptanceNotes: string | null }
export interface SupplyEvent { id: string; entityType: string; entityId: string; action: string; fromStatus: string | null; toStatus: string | null; comment: string | null; actor: SupplyUser; createdAt: string }
export interface SupplyRegister { suppliers: Supplier[]; contracts: SupplierContract[]; requests: PurchaseRequest[]; deliveries: SupplierDelivery[]; reviews: SupplierReview[]; events: SupplyEvent[] }
export interface SupplySummary { totalSuppliers: number; qualifiedSuppliers: number; pendingQualifications: number; expiringQualifications: number; activeContracts: number; expiringContracts: number; pendingRequests: number; lateDeliveries: number; averagePerformance: number; belowStandardSuppliers: number }
export interface SupplyOptions { users: SupplyUser[]; projects: SupplyProject[]; suppliers: Array<Pick<Supplier, 'id' | 'supplierCode' | 'legalName' | 'status'>>; contracts: Array<Pick<SupplierContract, 'id' | 'contractNumber' | 'title' | 'supplierId'>>; requests: Array<Pick<PurchaseRequest, 'id' | 'requestNumber' | 'title'> & { supplierId: string | null }> }
