export type TrainingTab = 'courses' | 'competencies' | 'requirements' | 'sessions' | 'certifications' | 'workflow';
export type TrainingCreateKind = 'course' | 'courseCompetency' | 'competency' | 'profile' | 'requirement' | 'session' | 'enrollment' | 'attendance' | 'assessment' | 'certification';
export interface TrainingUser { id: string; name: string; email: string; department: string | null; role: string }
export interface TrainingProject { id: string; code: string; title: string; department: string; managerId: string }
export interface TrainingEvidence { id: string; name: string; url: string; mimeType: string | null; notes: string | null; uploadedBy: TrainingUser; createdAt: string }
export interface Competency { id: string; code: string; name: string; category: string; description: string; isActive: boolean }
export interface StaffCompetency { id: string; userId: string; user: TrainingUser; competencyId: string; competency: Competency; currentLevel: number; targetLevel: number; assessedAt: string | null; assessedBy: TrainingUser | null; notes: string | null; evidence: TrainingEvidence[] }
export interface CourseCompetency { id: string; targetLevel: number; competency: Competency }
export interface TrainingCourse { id: string; code: string; title: string; category: string; description: string; provider: string | null; deliveryMode: string; durationHours: string; validityMonths: number | null; mandatory: boolean; defaultCost: string; currency: string; status: string; competencies: CourseCompetency[] }
export interface TrainingRequirement { id: string; name: string; role: string | null; department: string | null; course: TrainingCourse | null; competency: Competency | null; requiredLevel: number | null; dueWithinDays: number; renewalMonths: number | null; isActive: boolean; notes: string | null }
export interface TrainingAttendance { id: string; sessionDate: string; status: string; hours: string; notes: string | null; recordedBy: TrainingUser }
export interface TrainingAssessment { id: string; type: string; score: string; maximumScore: string; assessedAt: string; assessor: TrainingUser; notes: string | null; evidence: TrainingEvidence[] }
export interface TrainingEnrollment { id: string; sessionId: string; userId: string; user: TrainingUser; nominatedBy: TrainingUser; status: string; attendancePercentage: string; completedAt: string | null; feedback: string | null; effectivenessScore: number | null; attendance: TrainingAttendance[]; assessments: TrainingAssessment[]; certifications: StaffCertification[]; evidence: TrainingEvidence[] }
export interface TrainingSession { id: string; courseId: string; course: TrainingCourse; project: TrainingProject | null; sessionCode: string; title: string; startDate: string; endDate: string; location: string; instructor: string; capacity: number; plannedCost: string; actualCost: string; currency: string; status: string; coordinatorId: string; coordinator: TrainingUser; submittedBy: TrainingUser | null; reviewedBy: TrainingUser | null; reviewComment: string | null; enrollments: TrainingEnrollment[]; evidence: TrainingEvidence[] }
export interface StaffCertification { id: string; userId: string; user: TrainingUser; course: TrainingCourse | null; competency: Competency | null; enrollmentId: string | null; certificateNumber: string; title: string; issuer: string; issuedAt: string; expiresAt: string | null; status: string; effectiveStatus: string; issuedBy: TrainingUser; verifiedBy: TrainingUser | null; verifiedAt: string | null; notes: string | null; evidence: TrainingEvidence[] }
export interface TrainingEvent { id: string; entityType: string; entityId: string; action: string; fromStatus: string | null; toStatus: string | null; comment: string | null; actor: TrainingUser; createdAt: string }
export interface TrainingRegister { competencies: Competency[]; profiles: StaffCompetency[]; courses: TrainingCourse[]; requirements: TrainingRequirement[]; sessions: TrainingSession[]; certifications: StaffCertification[]; events: TrainingEvent[] }
export interface TrainingSummary { activeCourses: number; upcomingSessions: number; activeParticipants: number; completionRate: number; requirementCompliance: number; applicableRequirements: number; unmetRequirements: number; skillsGaps: number; expiringCertifications: number; trainingHours: number; plannedCost: number; actualCost: number; averageEffectiveness: number }
export interface TrainingOptions { users: TrainingUser[]; projects: TrainingProject[]; competencies: Competency[]; courses: TrainingCourse[]; sessions: Array<Pick<TrainingSession, 'id' | 'sessionCode' | 'title' | 'courseId' | 'status'>>; enrollments: Array<Pick<TrainingEnrollment, 'id' | 'sessionId' | 'userId' | 'status'>> }
