import { createHash } from 'crypto';
import { Router } from 'express';
import {
  BudgetStatus, CertificationStatus, ComplianceObligationStatus, FinanceEntryType, FinanceRecordStatus,
  FormalReportStatus, FormalReportType, KpiMeasurementStatus, NonConformityStatus, PermitStatus, Prisma,
  ProjectStatus, ReportTemplateStatus, Role, SupplierContractStatus, SupplierStatus, TrainingEnrollmentStatus,
} from '@prisma/client';
import { prisma } from '@smart-oil-field/database';
import { z } from 'zod';
import { requireAuth } from '../auth';

const router = Router();
router.use(requireAuth);

const uuid = z.string().uuid();
const optionalText = (max: number) => z.string().trim().max(max).nullable().optional();
const secureUrl = z.string().trim().url().max(2000).refine((value) => value.startsWith('https://') || value.startsWith('http://localhost'), 'Use an HTTPS evidence URL');
const userSelect = { id: true, name: true, email: true, department: true, role: true };
const templateInclude = { createdBy: { select: userSelect }, submittedBy: { select: userSelect }, reviewedBy: { select: userSelect } };
const versionInclude = { createdBy: { select: userSelect }, evidence: { include: { uploadedBy: { select: userSelect } }, orderBy: { createdAt: 'desc' as const } } };
const reportInclude = {
  template: true, project: { select: { id: true, code: true, title: true, department: true, managerId: true } },
  owner: { select: userSelect }, submittedBy: { select: userSelect }, reviewedBy: { select: userSelect }, signedBy: { select: userSelect }, publishedBy: { select: userSelect },
  versions: { include: versionInclude, orderBy: { version: 'desc' as const } }, evidence: { include: { uploadedBy: { select: userSelect } }, orderBy: { createdAt: 'desc' as const } },
};

const templateSchema = z.object({
  code: z.string().trim().min(3).max(60).regex(/^[A-Za-z0-9_./-]+$/).transform((value) => value.toUpperCase()), name: z.string().trim().min(4).max(240),
  type: z.nativeEnum(FormalReportType), description: z.string().trim().min(20).max(5000), sections: z.array(z.string().trim().min(2).max(160)).min(3).max(30),
  allowedRoles: z.array(z.nativeEnum(Role)).min(1),
});
const reportSchema = z.object({
  templateId: uuid, reference: z.string().trim().min(3).max(100).regex(/^[A-Za-z0-9_./-]+$/).transform((value) => value.toUpperCase()), title: z.string().trim().min(5).max(300),
  projectId: uuid.nullable().optional(), department: optionalText(160), periodStart: z.coerce.date(), periodEnd: z.coerce.date(),
  executiveSummary: z.string().trim().min(20).max(12000), findings: z.string().trim().min(10).max(12000), recommendations: z.string().trim().min(10).max(12000),
}).refine((value) => value.periodEnd >= value.periodStart, { message: 'Period end must be on or after period start', path: ['periodEnd'] });
const narrativeSchema = z.object({ executiveSummary: z.string().trim().min(20).max(12000), findings: z.string().trim().min(10).max(12000), recommendations: z.string().trim().min(10).max(12000) });
const evidenceSchema = z.object({ reportId: uuid, versionId: uuid.nullable().optional(), name: z.string().trim().min(2).max(240), url: secureUrl, mimeType: optionalText(120), notes: optionalText(2000) });

const templateManagers: Role[] = [Role.ADMINISTRATOR, Role.ME_OFFICER];
const signatories: Role[] = [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD];
const reviewerRoles: Record<FormalReportType, Role[]> = {
  PROJECT: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.ME_OFFICER], QUARTERLY: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.ME_OFFICER],
  ANNUAL: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.ME_OFFICER], FINANCE: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.FINANCE_OFFICER],
  COMPLIANCE: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.COMPLIANCE_OFFICER], SUPPLIER: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.SUPPLY_CHAIN_OFFICER],
  TRAINING: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.ME_OFFICER], DEPARTMENT: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD, Role.ME_OFFICER],
  EXECUTIVE: [Role.ADMINISTRATOR, Role.DEPARTMENT_HEAD],
};
const activeOutputStatuses: FormalReportStatus[] = [FormalReportStatus.APPROVED, FormalReportStatus.SIGNED, FormalReportStatus.PUBLISHED, FormalReportStatus.ARCHIVED];
const workflow = (actorId: string, action: string, fromStatus: string | null, toStatus: string | null, input: { reportId?: string; templateId?: string; comment?: string | null }) => prisma.formalReportWorkflowEvent.create({ data: { actorId, action, fromStatus, toStatus, reportId: input.reportId, templateId: input.templateId, comment: input.comment } });
const audit = (actorId: string, action: string, entityType: string, entityId: string) => prisma.auditLog.create({ data: { actorId, action, entityType, entityId } });
const checksum = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const number = (value: unknown) => Number(value || 0);
const round = (value: number) => Math.round(value * 100) / 100;
const escapeCsv = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`;
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]!));

type Scope = { projectId?: string | null; department?: string | null; periodStart: Date; periodEnd: Date };
const buildSnapshot = async (scope: Scope) => {
  const projectWhere: Prisma.ProjectWhereInput = { startDate: { lte: scope.periodEnd }, endDate: { gte: scope.periodStart }, ...(scope.projectId ? { id: scope.projectId } : {}), ...(scope.department ? { department: scope.department } : {}) };
  const [projects, budgets, indicators, obligations, permits, findings, suppliers, contracts, reviews, users, profiles, certifications, sessions, enrollments] = await Promise.all([
    prisma.project.findMany({ where: projectWhere, include: { milestones: true, risks: true } }),
    prisma.projectBudget.findMany({ where: { project: projectWhere }, include: { entries: { where: { transactionDate: { gte: scope.periodStart, lte: scope.periodEnd }, status: FinanceRecordStatus.APPROVED } } } }),
    prisma.kpiIndicator.findMany({ where: { framework: { project: projectWhere } }, include: { measurements: { where: { measuredAt: { gte: scope.periodStart, lte: scope.periodEnd }, status: KpiMeasurementStatus.VERIFIED } } } }),
    prisma.complianceObligation.findMany({ where: { ...(scope.projectId ? { projectId: scope.projectId } : {}), ...(scope.department ? { department: scope.department } : {}), dueDate: { lte: scope.periodEnd } } }),
    prisma.compliancePermit.findMany({ where: { ...(scope.projectId ? { projectId: scope.projectId } : {}), expiryDate: { gte: scope.periodStart } } }),
    prisma.nonConformity.findMany({ where: { ...(scope.projectId ? { projectId: scope.projectId } : {}), detectedAt: { lte: scope.periodEnd } } }),
    prisma.supplier.findMany(), prisma.supplierContract.findMany({ where: { ...(scope.projectId ? { projectId: scope.projectId } : {}), startDate: { lte: scope.periodEnd }, endDate: { gte: scope.periodStart } } }),
    prisma.supplierPerformanceReview.findMany({ where: { periodStart: { lte: scope.periodEnd }, periodEnd: { gte: scope.periodStart }, ...(scope.projectId ? { contract: { projectId: scope.projectId } } : {}) } }),
    prisma.user.findMany({ where: { isActive: true, ...(scope.department ? { department: scope.department } : {}) } }),
    prisma.staffCompetency.findMany({ where: { user: { isActive: true, ...(scope.department ? { department: scope.department } : {}) } } }),
    prisma.staffCertification.findMany({ where: { user: { isActive: true, ...(scope.department ? { department: scope.department } : {}) } } }),
    prisma.trainingSession.findMany({ where: { startDate: { lte: scope.periodEnd }, endDate: { gte: scope.periodStart }, ...(scope.projectId ? { projectId: scope.projectId } : {}), ...(scope.department ? { coordinator: { department: scope.department } } : {}) } }),
    prisma.trainingEnrollment.findMany({ where: { session: { startDate: { lte: scope.periodEnd }, endDate: { gte: scope.periodStart }, ...(scope.projectId ? { projectId: scope.projectId } : {}) }, ...(scope.department ? { user: { department: scope.department } } : {}) } }),
  ]);
  const approvedBudget = budgets.filter((item) => item.status === BudgetStatus.APPROVED || item.status === BudgetStatus.CLOSED).reduce((sum, item) => sum + number(item.approvedAmount), 0);
  const expenditure = budgets.flatMap((item) => item.entries).filter((item) => item.type === FinanceEntryType.EXPENDITURE).reduce((sum, item) => sum + number(item.amount), 0);
  const commitments = budgets.flatMap((item) => item.entries).filter((item) => item.type === FinanceEntryType.COMMITMENT).reduce((sum, item) => sum + number(item.amount), 0);
  const metrics = [
    { category: 'Projects', label: 'Projects in scope', value: projects.length }, { category: 'Projects', label: 'Average progress', value: `${projects.length ? round(projects.reduce((sum, item) => sum + item.progress, 0) / projects.length) : 0}%` },
    { category: 'Projects', label: 'Active projects', value: projects.filter((item) => item.status === ProjectStatus.ACTIVE).length }, { category: 'Projects', label: 'Open high/critical risks', value: projects.flatMap((item) => item.risks).filter((item) => ['HIGH', 'CRITICAL'].includes(item.level) && item.status !== 'CLOSED').length },
    { category: 'Finance', label: 'Approved budget', value: round(approvedBudget) }, { category: 'Finance', label: 'Approved expenditure', value: round(expenditure) }, { category: 'Finance', label: 'Approved commitments', value: round(commitments) }, { category: 'Finance', label: 'Budget utilization', value: `${approvedBudget ? round(expenditure / approvedBudget * 100) : 0}%` },
    { category: 'Results', label: 'Indicators', value: indicators.length }, { category: 'Results', label: 'Indicators reported', value: indicators.filter((item) => item.measurements.length > 0).length }, { category: 'Results', label: 'Reporting completeness', value: `${indicators.length ? round(indicators.filter((item) => item.measurements.length > 0).length / indicators.length * 100) : 100}%` },
    { category: 'Compliance', label: 'Obligations', value: obligations.length }, { category: 'Compliance', label: 'Compliant obligations', value: obligations.filter((item) => item.status === ComplianceObligationStatus.COMPLIANT).length }, { category: 'Compliance', label: 'Overdue/non-compliant', value: obligations.filter((item) => ([ComplianceObligationStatus.OVERDUE, ComplianceObligationStatus.NON_COMPLIANT] as ComplianceObligationStatus[]).includes(item.status)).length },
    { category: 'Compliance', label: 'Active permits', value: permits.filter((item) => item.status === PermitStatus.ACTIVE).length }, { category: 'Compliance', label: 'Open findings', value: findings.filter((item) => item.status !== NonConformityStatus.CLOSED).length },
    { category: 'Supply Chain', label: 'Qualified suppliers', value: suppliers.filter((item) => item.status === SupplierStatus.QUALIFIED).length }, { category: 'Supply Chain', label: 'Active contracts', value: contracts.filter((item) => item.status === SupplierContractStatus.ACTIVE).length }, { category: 'Supply Chain', label: 'Average supplier score', value: reviews.length ? round(reviews.reduce((sum, item) => sum + number(item.overallScore), 0) / reviews.length) : 0 },
    { category: 'Workforce', label: 'Active staff', value: users.length }, { category: 'Workforce', label: 'Competency gaps', value: profiles.filter((item) => item.currentLevel < item.targetLevel).length }, { category: 'Workforce', label: 'Training sessions', value: sessions.length }, { category: 'Workforce', label: 'Completed enrollments', value: enrollments.filter((item) => item.status === TrainingEnrollmentStatus.COMPLETED).length },
    { category: 'Workforce', label: 'Verified active certificates', value: certifications.filter((item) => item.status === CertificationStatus.ACTIVE && item.verifiedById).length },
  ];
  return { generatedAt: new Date().toISOString(), scope: { projectId: scope.projectId || null, department: scope.department || null, periodStart: scope.periodStart.toISOString(), periodEnd: scope.periodEnd.toISOString() }, metrics };
};

const buildContent = (sections: unknown, snapshot: Awaited<ReturnType<typeof buildSnapshot>>) => {
  const names = Array.isArray(sections) ? sections.map(String) : [];
  return { sections: names.map((title) => ({ title, metrics: snapshot.metrics.filter((item) => title.toLowerCase().split(/\s+/).some((word) => item.category.toLowerCase().includes(word) || item.label.toLowerCase().includes(word))).slice(0, 8) })) };
};
const latestVersion = (report: { currentVersion: number; versions: Array<{ version: number; checksum: string; executiveSummary: string; findings: string; recommendations: string; content: unknown; sourceSnapshot: unknown }> }) => report.versions.find((item) => item.version === report.currentVersion);
const canAuthor = (user: { id: string; role: Role; department: string | null }, template: { allowedRoles: Role[] }, scope: { project?: { managerId: string } | null; department?: string | null }) => user.role === Role.ADMINISTRATOR || (template.allowedRoles.includes(user.role) && (user.role !== Role.PROJECT_MANAGER || scope.project?.managerId === user.id) && (user.role !== Role.DEPARTMENT_HEAD || !scope.department || scope.department === user.department));

router.get('/options', async (req, res, next) => { try { const [templates, projects, users] = await Promise.all([prisma.formalReportTemplate.findMany({ where: { status: ReportTemplateStatus.ACTIVE, ...(req.authUser!.role === Role.ADMINISTRATOR ? {} : { allowedRoles: { has: req.authUser!.role } }) }, orderBy: { name: 'asc' } }), prisma.project.findMany({ orderBy: { title: 'asc' }, select: { id: true, code: true, title: true, department: true, managerId: true } }), prisma.user.findMany({ where: { isActive: true }, select: { department: true } })]); return res.json({ templates, projects, departments: [...new Set(users.map((item) => item.department).filter(Boolean))].sort() }); } catch (error) { return next(error); } });

router.get('/overview', async (_req, res, next) => { try { const reports = await prisma.formalReport.findMany({ select: { status: true, type: true, periodEnd: true, publishedAt: true } }); const templates = await prisma.formalReportTemplate.count({ where: { status: ReportTemplateStatus.ACTIVE } }); return res.json({ summary: { totalReports: reports.length, activeTemplates: templates, awaitingReview: reports.filter((item) => item.status === FormalReportStatus.SUBMITTED).length, awaitingSignature: reports.filter((item) => item.status === FormalReportStatus.APPROVED).length, published: reports.filter((item) => item.status === FormalReportStatus.PUBLISHED).length, overdueDrafts: reports.filter((item) => ([FormalReportStatus.DRAFT, FormalReportStatus.REJECTED] as FormalReportStatus[]).includes(item.status) && item.periodEnd < new Date()).length } }); } catch (error) { return next(error); } });

router.get('/register', async (_req, res, next) => { try { const [templates, reports, events] = await Promise.all([prisma.formalReportTemplate.findMany({ include: templateInclude, orderBy: { code: 'asc' } }), prisma.formalReport.findMany({ include: reportInclude, orderBy: { updatedAt: 'desc' } }), prisma.formalReportWorkflowEvent.findMany({ include: { actor: { select: userSelect } }, orderBy: { createdAt: 'desc' }, take: 500 })]); return res.json({ templates, reports, events }); } catch (error) { return next(error); } });

router.post('/templates', async (req, res, next) => { try { if (!templateManagers.includes(req.authUser!.role)) return res.status(403).json({ message: 'Only Administrators and M&E Officers can create report templates' }); const template = await prisma.formalReportTemplate.create({ data: { ...templateSchema.parse(req.body), createdById: req.authUser!.id }, include: templateInclude }); await workflow(req.authUser!.id, 'CREATED', null, template.status, { templateId: template.id }); return res.status(201).json({ template }); } catch (error) { return next(error); } });
router.post('/templates/:id/submit', async (req, res, next) => { try { const current = await prisma.formalReportTemplate.findUnique({ where: { id: req.params.id } }); if (!current) return res.status(404).json({ message: 'Report template not found' }); if (current.createdById !== req.authUser!.id && req.authUser!.role !== Role.ADMINISTRATOR) return res.status(403).json({ message: 'You cannot submit this template' }); if (!([ReportTemplateStatus.DRAFT, ReportTemplateStatus.REJECTED] as ReportTemplateStatus[]).includes(current.status)) return res.status(409).json({ message: 'Only draft or rejected templates can be submitted' }); const item = await prisma.formalReportTemplate.update({ where: { id: current.id }, data: { status: ReportTemplateStatus.SUBMITTED, submittedById: req.authUser!.id, submittedAt: new Date(), reviewedById: null, reviewedAt: null, reviewComment: null }, include: templateInclude }); await workflow(req.authUser!.id, 'SUBMITTED', current.status, item.status, { templateId: item.id }); return res.json({ template: item }); } catch (error) { return next(error); } });
router.post('/templates/:id/decision', async (req, res, next) => { try { if (req.authUser!.role !== Role.ADMINISTRATOR) return res.status(403).json({ message: 'Only Administrators can approve report templates' }); const current = await prisma.formalReportTemplate.findUnique({ where: { id: req.params.id } }); if (!current) return res.status(404).json({ message: 'Report template not found' }); if (current.status !== ReportTemplateStatus.SUBMITTED) return res.status(409).json({ message: 'Only submitted templates can be decided' }); if (current.submittedById === req.authUser!.id) return res.status(403).json({ message: 'A template submitter cannot approve their own template' }); const input = z.object({ approved: z.boolean(), comment: optionalText(3000) }).parse(req.body); const status = input.approved ? ReportTemplateStatus.ACTIVE : ReportTemplateStatus.REJECTED; const item = await prisma.formalReportTemplate.update({ where: { id: current.id }, data: { status, reviewedById: req.authUser!.id, reviewedAt: new Date(), reviewComment: input.comment }, include: templateInclude }); await workflow(req.authUser!.id, input.approved ? 'APPROVED' : 'REJECTED', current.status, status, { templateId: item.id, comment: input.comment }); return res.json({ template: item }); } catch (error) { return next(error); } });

router.post('/generate', async (req, res, next) => { try { const input = reportSchema.parse(req.body); const template = await prisma.formalReportTemplate.findUnique({ where: { id: input.templateId } }); if (!template || template.status !== ReportTemplateStatus.ACTIVE) return res.status(409).json({ message: 'Reports require an active controlled template' }); const project = input.projectId ? await prisma.project.findUnique({ where: { id: input.projectId } }) : null; if (template.type === FormalReportType.PROJECT && !project) return res.status(400).json({ message: 'Project reports require a project' }); if (template.type === FormalReportType.DEPARTMENT && !input.department) return res.status(400).json({ message: 'Department reports require a department' }); if (!canAuthor(req.authUser!, template, { project, department: input.department })) return res.status(403).json({ message: 'Your role cannot generate this report scope' }); const snapshot = await buildSnapshot(input); const content = buildContent(template.sections, snapshot); const signedContent = { executiveSummary: input.executiveSummary, findings: input.findings, recommendations: input.recommendations, content, sourceSnapshot: snapshot }; const report = await prisma.formalReport.create({ data: { reference: input.reference, title: input.title, type: template.type, templateId: template.id, projectId: input.projectId, department: input.department, periodStart: input.periodStart, periodEnd: input.periodEnd, ownerId: req.authUser!.id, versions: { create: { version: 1, ...signedContent, checksum: checksum(signedContent), createdById: req.authUser!.id } } }, include: reportInclude }); await Promise.all([workflow(req.authUser!.id, 'GENERATED', null, report.status, { reportId: report.id }), audit(req.authUser!.id, 'FORMAL_REPORT_GENERATED', 'FormalReport', report.id)]); return res.status(201).json({ report }); } catch (error) { return next(error); } });

router.post('/reports/:id/revise', async (req, res, next) => { try { const current = await prisma.formalReport.findUnique({ where: { id: req.params.id }, include: reportInclude }); if (!current) return res.status(404).json({ message: 'Formal report not found' }); if (current.ownerId !== req.authUser!.id && req.authUser!.role !== Role.ADMINISTRATOR) return res.status(403).json({ message: 'Only the report owner can create a revision' }); if (!([FormalReportStatus.DRAFT, FormalReportStatus.REJECTED] as FormalReportStatus[]).includes(current.status)) return res.status(409).json({ message: 'Only draft or rejected reports can be revised' }); const narrative = narrativeSchema.parse(req.body); const snapshot = await buildSnapshot(current); const content = buildContent(current.template.sections, snapshot); const version = current.currentVersion + 1; const signedContent = { ...narrative, content, sourceSnapshot: snapshot }; const [, item] = await prisma.$transaction([prisma.formalReportVersion.create({ data: { reportId: current.id, version, ...signedContent, checksum: checksum(signedContent), createdById: req.authUser!.id } }), prisma.formalReport.update({ where: { id: current.id }, data: { currentVersion: version, status: FormalReportStatus.DRAFT, submittedById: null, reviewedById: null, signedById: null, publishedById: null, submittedAt: null, reviewedAt: null, signedAt: null, publishedAt: null, reviewComment: null }, include: reportInclude })]); await workflow(req.authUser!.id, 'REVISED', current.status, item.status, { reportId: item.id, comment: `Version ${version}` }); return res.json({ report: item }); } catch (error) { return next(error); } });
router.post('/reports/:id/submit', async (req, res, next) => { try { const current = await prisma.formalReport.findUnique({ where: { id: req.params.id } }); if (!current) return res.status(404).json({ message: 'Formal report not found' }); if (current.ownerId !== req.authUser!.id && req.authUser!.role !== Role.ADMINISTRATOR) return res.status(403).json({ message: 'Only the report owner can submit it' }); if (current.status !== FormalReportStatus.DRAFT) return res.status(409).json({ message: 'Only draft reports can be submitted' }); const item = await prisma.formalReport.update({ where: { id: current.id }, data: { status: FormalReportStatus.SUBMITTED, submittedById: req.authUser!.id, submittedAt: new Date() }, include: reportInclude }); await workflow(req.authUser!.id, 'SUBMITTED', current.status, item.status, { reportId: item.id }); return res.json({ report: item }); } catch (error) { return next(error); } });
router.post('/reports/:id/decision', async (req, res, next) => { try { const current = await prisma.formalReport.findUnique({ where: { id: req.params.id } }); if (!current) return res.status(404).json({ message: 'Formal report not found' }); if (!reviewerRoles[current.type].includes(req.authUser!.role)) return res.status(403).json({ message: 'Your role cannot review this report type' }); if (current.status !== FormalReportStatus.SUBMITTED) return res.status(409).json({ message: 'Only submitted reports can be reviewed' }); if (current.submittedById === req.authUser!.id || current.ownerId === req.authUser!.id) return res.status(403).json({ message: 'A report author or submitter cannot approve their own report' }); const input = z.object({ approved: z.boolean(), comment: optionalText(5000) }).parse(req.body); const status = input.approved ? FormalReportStatus.APPROVED : FormalReportStatus.REJECTED; const item = await prisma.formalReport.update({ where: { id: current.id }, data: { status, reviewedById: req.authUser!.id, reviewedAt: new Date(), reviewComment: input.comment }, include: reportInclude }); await Promise.all([workflow(req.authUser!.id, input.approved ? 'APPROVED' : 'REJECTED', current.status, status, { reportId: item.id, comment: input.comment }), audit(req.authUser!.id, 'FORMAL_REPORT_DECIDED', 'FormalReport', item.id)]); return res.json({ report: item }); } catch (error) { return next(error); } });
router.post('/reports/:id/sign', async (req, res, next) => { try { if (!signatories.includes(req.authUser!.role)) return res.status(403).json({ message: 'Only Administrators and Department Heads can sign reports' }); const current = await prisma.formalReport.findUnique({ where: { id: req.params.id }, include: { versions: true } }); if (!current) return res.status(404).json({ message: 'Formal report not found' }); if (current.status !== FormalReportStatus.APPROVED) return res.status(409).json({ message: 'Only approved reports can be signed' }); if (current.ownerId === req.authUser!.id || current.submittedById === req.authUser!.id) return res.status(403).json({ message: 'A report author or submitter cannot sign their own report' }); const version = latestVersion(current); if (!version) return res.status(409).json({ message: 'Current report version is missing' }); const recalculated = checksum({ executiveSummary: version.executiveSummary, findings: version.findings, recommendations: version.recommendations, content: version.content, sourceSnapshot: version.sourceSnapshot }); if (recalculated !== version.checksum) return res.status(409).json({ message: 'Report integrity verification failed' }); const item = await prisma.formalReport.update({ where: { id: current.id }, data: { status: FormalReportStatus.SIGNED, signedById: req.authUser!.id, signedAt: new Date() }, include: reportInclude }); await Promise.all([workflow(req.authUser!.id, 'SIGNED', current.status, item.status, { reportId: item.id, comment: `SHA-256 ${version.checksum}` }), audit(req.authUser!.id, 'FORMAL_REPORT_SIGNED', 'FormalReport', item.id)]); return res.json({ report: item }); } catch (error) { return next(error); } });
router.post('/reports/:id/publish', async (req, res, next) => { try { if (!signatories.includes(req.authUser!.role)) return res.status(403).json({ message: 'Only Administrators and Department Heads can publish reports' }); const current = await prisma.formalReport.findUnique({ where: { id: req.params.id } }); if (!current) return res.status(404).json({ message: 'Formal report not found' }); if (current.status !== FormalReportStatus.SIGNED) return res.status(409).json({ message: 'Only signed reports can be published' }); const item = await prisma.formalReport.update({ where: { id: current.id }, data: { status: FormalReportStatus.PUBLISHED, publishedById: req.authUser!.id, publishedAt: new Date() }, include: reportInclude }); await workflow(req.authUser!.id, 'PUBLISHED', current.status, item.status, { reportId: item.id }); return res.json({ report: item }); } catch (error) { return next(error); } });
router.post('/reports/:id/archive', async (req, res, next) => { try { if (req.authUser!.role !== Role.ADMINISTRATOR) return res.status(403).json({ message: 'Only Administrators can archive formal reports' }); const current = await prisma.formalReport.findUnique({ where: { id: req.params.id } }); if (!current) return res.status(404).json({ message: 'Formal report not found' }); if (current.status !== FormalReportStatus.PUBLISHED) return res.status(409).json({ message: 'Only published reports can be archived' }); const item = await prisma.formalReport.update({ where: { id: current.id }, data: { status: FormalReportStatus.ARCHIVED, archivedAt: new Date() }, include: reportInclude }); await workflow(req.authUser!.id, 'ARCHIVED', current.status, item.status, { reportId: item.id }); return res.json({ report: item }); } catch (error) { return next(error); } });
router.post('/evidence', async (req, res, next) => { try { const input = evidenceSchema.parse(req.body); const report = await prisma.formalReport.findUnique({ where: { id: input.reportId } }); if (!report) return res.status(404).json({ message: 'Formal report not found' }); if (report.ownerId !== req.authUser!.id && req.authUser!.role !== Role.ADMINISTRATOR) return res.status(403).json({ message: 'Only the report owner can attach evidence' }); if (!([FormalReportStatus.DRAFT, FormalReportStatus.REJECTED] as FormalReportStatus[]).includes(report.status)) return res.status(409).json({ message: 'Evidence is locked after report submission' }); if (input.versionId) { const version = await prisma.formalReportVersion.findUnique({ where: { id: input.versionId } }); if (!version || version.reportId !== report.id) return res.status(400).json({ message: 'Evidence version must belong to the selected report' }); } const evidence = await prisma.formalReportEvidence.create({ data: { ...input, uploadedById: req.authUser!.id }, include: { uploadedBy: { select: userSelect } } }); await audit(req.authUser!.id, 'FORMAL_REPORT_EVIDENCE_ATTACHED', 'FormalReportEvidence', evidence.id); return res.status(201).json({ evidence }); } catch (error) { return next(error); } });

const getExportable = async (id: string) => { const report = await prisma.formalReport.findUnique({ where: { id }, include: reportInclude }); if (!report || !activeOutputStatuses.includes(report.status)) return null; const version = latestVersion(report); if (!version) return null; const recalculated = checksum({ executiveSummary: version.executiveSummary, findings: version.findings, recommendations: version.recommendations, content: version.content, sourceSnapshot: version.sourceSnapshot }); return recalculated === version.checksum ? { report, version } : null; };
router.get('/reports/:id/render.html', async (req, res, next) => { try { const result = await getExportable(req.params.id); if (!result) return res.status(409).json({ message: 'Only integrity-verified approved reports can be rendered' }); const { report, version } = result; const snapshot = version.sourceSnapshot as { metrics?: Array<{ category: string; label: string; value: unknown }> }; const rows = (snapshot.metrics || []).map((metric) => `<tr><td>${escapeHtml(metric.category)}</td><td>${escapeHtml(metric.label)}</td><td>${escapeHtml(metric.value)}</td></tr>`).join(''); const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report.reference)} · ${escapeHtml(report.title)}</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#102f46;line-height:1.5}header{border-bottom:4px solid #0b7895;margin-bottom:24px}h1{margin-bottom:4px}h2{color:#0b7895;border-bottom:1px solid #ccd8df;padding-bottom:6px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccd8df;padding:8px;text-align:left}th{background:#eaf2f5}.meta{color:#526b7a}.sign{margin-top:40px;padding-top:16px;border-top:1px solid #789}footer{margin-top:30px;font-size:11px;color:#607d8b}</style></head><body><header><h1>${escapeHtml(report.title)}</h1><p class="meta">${escapeHtml(report.reference)} · ${escapeHtml(report.type)} · Version ${report.currentVersion}<br>${escapeHtml(report.periodStart.toISOString().slice(0, 10))} to ${escapeHtml(report.periodEnd.toISOString().slice(0, 10))}</p></header><h2>Executive summary</h2><p>${escapeHtml(version.executiveSummary)}</p><h2>Performance evidence</h2><table><thead><tr><th>Area</th><th>Indicator</th><th>Value</th></tr></thead><tbody>${rows}</tbody></table><h2>Findings</h2><p>${escapeHtml(version.findings)}</p><h2>Recommendations</h2><p>${escapeHtml(version.recommendations)}</p><div class="sign"><strong>Approved by:</strong> ${escapeHtml(report.reviewedBy?.name || 'Pending')}<br><strong>Signed by:</strong> ${escapeHtml(report.signedBy?.name || 'Pending')} ${report.signedAt ? `on ${escapeHtml(report.signedAt.toISOString().slice(0, 10))}` : ''}</div><footer>Integrity checksum: ${escapeHtml(version.checksum)} · Generated by SMART Oil Field PMS</footer></body></html>`; res.set('Cache-Control', 'private, no-store'); res.type('html'); return res.send(html); } catch (error) { return next(error); } });
router.get('/reports/:id/export.csv', async (req, res, next) => { try { const result = await getExportable(req.params.id); if (!result) return res.status(409).json({ message: 'Only integrity-verified approved reports can be exported' }); const snapshot = result.version.sourceSnapshot as { metrics?: Array<{ category: string; label: string; value: unknown }> }; const rows = (snapshot.metrics || []).map((metric) => [metric.category, metric.label, metric.value].map(escapeCsv).join(',')); res.set('Cache-Control', 'private, no-store'); res.type('text/csv').attachment(`${result.report.reference.toLowerCase()}-v${result.report.currentVersion}.csv`); return res.send(['Category,Indicator,Value', ...rows].join('\n')); } catch (error) { return next(error); } });

export default router;
