import { createHash } from 'crypto';
import bcrypt from 'bcryptjs';
import request from 'supertest';
import { beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { FormalReportStatus, FormalReportType, ReportTemplateStatus, Role, User } from '@prisma/client';

const prismaMock = vi.hoisted(() => ({
  user: { findUnique: vi.fn(), findMany: vi.fn(), update: vi.fn() }, project: { findMany: vi.fn(), findUnique: vi.fn() },
  projectBudget: { findMany: vi.fn() }, kpiIndicator: { findMany: vi.fn() }, complianceObligation: { findMany: vi.fn() }, compliancePermit: { findMany: vi.fn() }, nonConformity: { findMany: vi.fn() },
  supplier: { findMany: vi.fn() }, supplierContract: { findMany: vi.fn() }, supplierPerformanceReview: { findMany: vi.fn() }, staffCompetency: { findMany: vi.fn() }, staffCertification: { findMany: vi.fn() }, trainingSession: { findMany: vi.fn() }, trainingEnrollment: { findMany: vi.fn() },
  formalReportTemplate: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
  formalReport: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() }, formalReportVersion: { findUnique: vi.fn(), create: vi.fn() }, formalReportEvidence: { create: vi.fn() },
  formalReportWorkflowEvent: { findMany: vi.fn(), create: vi.fn() }, auditLog: { create: vi.fn() },
  $transaction: vi.fn(), $queryRaw: vi.fn(), $disconnect: vi.fn(),
}));
vi.mock('@smart-oil-field/database', () => ({ prisma: prismaMock }));
import { createApp } from '../src/app';

const userId = 'dff73f65-8808-46e5-a347-9947280baaa4'; const otherId = '6533f167-b17a-4ec9-b35a-cbb1ac99079e';
const templateId = 'cded935f-c715-44eb-92d9-e20f95f83a55'; const reportId = '5ba9660b-0190-4f2a-b19a-00cb26d369b4'; const versionId = '85e4a9db-0d26-4bbd-b7dc-ecf3bf699f95'; const projectId = 'a104b8d9-0a7c-4965-ae69-e98dc81d1bc3';
const makeUser = (role: Role): User => ({ id: userId, name: 'Report User', email: 'reports@example.com', passwordHash: '', role, department: 'Operations', walletAddress: null, isActive: true, tokenVersion: 0, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() });
const reportUser = { id: userId, name: 'Report User', email: 'reports@example.com', role: Role.PROJECT_MANAGER, department: 'Operations' };
const template = { id: templateId, code: 'PMS-PROJECT', name: 'Project Report', type: FormalReportType.PROJECT, description: 'Controlled project performance report template.', sections: ['Executive summary', 'Projects', 'Finance'], allowedRoles: [Role.ADMINISTRATOR, Role.PROJECT_MANAGER, Role.DEPARTMENT_HEAD], isSystem: true, status: ReportTemplateStatus.ACTIVE, version: 1, createdById: otherId, submittedById: null, reviewedById: null, submittedAt: null, reviewedAt: null, reviewComment: null, createdAt: new Date(), updatedAt: new Date(), createdBy: reportUser, submittedBy: null, reviewedBy: null };
const project = { id: projectId, code: 'PRJ-001', title: 'Well Integrity', department: 'Operations', location: 'Unity', managerId: userId, startDate: new Date('2026-01-01'), endDate: new Date('2026-12-31'), status: 'ACTIVE', progress: 50, createdAt: new Date(), updatedAt: new Date(), milestones: [], risks: [] };
const sourceSnapshot = { generatedAt: '2026-08-11T00:00:00.000Z', scope: { projectId, department: null, periodStart: '2026-01-01T00:00:00.000Z', periodEnd: '2026-03-31T00:00:00.000Z' }, metrics: [{ category: 'Projects', label: 'Projects in scope', value: 1 }] };
const content = { sections: [{ title: 'Projects', metrics: sourceSnapshot.metrics }] }; const narrative = { executiveSummary: 'A complete executive summary for the reporting period.', findings: 'Project delivery remained on plan.', recommendations: 'Continue monthly performance assurance.' };
const digest = createHash('sha256').update(JSON.stringify({ ...narrative, content, sourceSnapshot })).digest('hex');
const version = { id: versionId, reportId, version: 1, ...narrative, content, sourceSnapshot, checksum: digest, createdById: userId, createdAt: new Date(), createdBy: reportUser, evidence: [] };
const formalReport = { id: reportId, reference: 'RPT-001', title: 'Q1 Well Integrity Report', type: FormalReportType.PROJECT, templateId, projectId, department: null, periodStart: new Date('2026-01-01'), periodEnd: new Date('2026-03-31'), status: FormalReportStatus.DRAFT, currentVersion: 1, ownerId: userId, submittedById: null, reviewedById: null, signedById: null, publishedById: null, submittedAt: null, reviewedAt: null, signedAt: null, publishedAt: null, archivedAt: null, reviewComment: null, createdAt: new Date(), updatedAt: new Date(), template, project, owner: reportUser, submittedBy: null, reviewedBy: null, signedBy: null, publishedBy: null, versions: [version], evidence: [] };

describe('formal reporting and analytics HTTP integration', () => {
  let user: User;
  beforeAll(() => { process.env.NODE_ENV = 'test'; process.env.JWT_SECRET = 'formal-reporting-tests-secret-that-is-definitely-at-least-sixty-four-characters'; process.env.JWT_ISSUER = 'smart-oil-field-api-test'; process.env.JWT_AUDIENCE = 'smart-oil-field-services-test'; });
  beforeEach(async () => {
    vi.clearAllMocks(); user = makeUser(Role.VIEWER); user.passwordHash = await bcrypt.hash('SecurePassword123!', 4);
    prismaMock.user.findUnique.mockImplementation(async ({ where }: { where: { id?: string; email?: string } }) => where.id === user.id || where.email === user.email ? user : null); prismaMock.user.update.mockResolvedValue(user); prismaMock.user.findMany.mockResolvedValue([user]);
    prismaMock.project.findMany.mockResolvedValue([project]); prismaMock.project.findUnique.mockResolvedValue(project); prismaMock.projectBudget.findMany.mockResolvedValue([]); prismaMock.kpiIndicator.findMany.mockResolvedValue([]); prismaMock.complianceObligation.findMany.mockResolvedValue([]); prismaMock.compliancePermit.findMany.mockResolvedValue([]); prismaMock.nonConformity.findMany.mockResolvedValue([]); prismaMock.supplier.findMany.mockResolvedValue([]); prismaMock.supplierContract.findMany.mockResolvedValue([]); prismaMock.supplierPerformanceReview.findMany.mockResolvedValue([]); prismaMock.staffCompetency.findMany.mockResolvedValue([]); prismaMock.staffCertification.findMany.mockResolvedValue([]); prismaMock.trainingSession.findMany.mockResolvedValue([]); prismaMock.trainingEnrollment.findMany.mockResolvedValue([]);
    prismaMock.formalReportTemplate.findMany.mockResolvedValue([template]); prismaMock.formalReportTemplate.findUnique.mockResolvedValue(template); prismaMock.formalReportTemplate.count.mockResolvedValue(1); prismaMock.formalReportTemplate.create.mockResolvedValue(template); prismaMock.formalReportTemplate.update.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({ ...template, ...data }));
    prismaMock.formalReport.findMany.mockResolvedValue([formalReport]); prismaMock.formalReport.findUnique.mockResolvedValue(formalReport); prismaMock.formalReport.create.mockResolvedValue(formalReport); prismaMock.formalReport.update.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({ ...formalReport, ...data }));
    prismaMock.formalReportVersion.findUnique.mockResolvedValue(version); prismaMock.formalReportVersion.create.mockResolvedValue(version); prismaMock.formalReportEvidence.create.mockResolvedValue({ id: 'evidence-id' }); prismaMock.formalReportWorkflowEvent.findMany.mockResolvedValue([]); prismaMock.formalReportWorkflowEvent.create.mockResolvedValue({}); prismaMock.auditLog.create.mockResolvedValue({}); prismaMock.$transaction.mockImplementation(async (operations: Array<Promise<unknown>>) => Promise.all(operations));
  });
  const login = async () => { const agent = request.agent(createApp()); await agent.post('/api/auth/login').send({ email: user.email, password: 'SecurePassword123!' }); return agent; };
  const generateBody = { templateId, reference: 'RPT-001', title: 'Q1 Well Integrity Report', projectId, periodStart: '2026-01-01', periodEnd: '2026-03-31', ...narrative };

  it('provides authenticated portfolio reporting analytics', async () => { const response = await (await login()).get('/api/reports/overview'); expect(response.status).toBe(200); expect(response.body.summary.activeTemplates).toBe(1); });
  it('prevents viewers from generating controlled reports', async () => { const response = await (await login()).post('/api/reports/generate').send(generateBody); expect(response.status).toBe(403); expect(prismaMock.formalReport.create).not.toHaveBeenCalled(); });
  it('allows a Project Manager to generate a report for their own project', async () => { user = { ...user, role: Role.PROJECT_MANAGER }; const response = await (await login()).post('/api/reports/generate').send(generateBody); expect(response.status).toBe(201); expect(prismaMock.formalReport.create).toHaveBeenCalledOnce(); });
  it('prevents a Project Manager reporting another manager project', async () => { user = { ...user, role: Role.PROJECT_MANAGER }; prismaMock.project.findUnique.mockResolvedValue({ ...project, managerId: otherId }); const response = await (await login()).post('/api/reports/generate').send(generateBody); expect(response.status).toBe(403); });
  it('requires a project scope for project reports', async () => { user = { ...user, role: Role.ADMINISTRATOR }; const response = await (await login()).post('/api/reports/generate').send({ ...generateBody, projectId: null }); expect(response.status).toBe(400); });
  it('prevents a template submitter approving their own template', async () => { user = { ...user, role: Role.ADMINISTRATOR }; prismaMock.formalReportTemplate.findUnique.mockResolvedValue({ ...template, status: ReportTemplateStatus.SUBMITTED, submittedById: userId }); const response = await (await login()).post(`/api/reports/templates/${templateId}/decision`).send({ approved: true }); expect(response.status).toBe(403); });
  it('prevents report authors approving their own submission', async () => { user = { ...user, role: Role.DEPARTMENT_HEAD }; prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.SUBMITTED, submittedById: userId }); const response = await (await login()).post(`/api/reports/reports/${reportId}/decision`).send({ approved: true }); expect(response.status).toBe(403); });
  it('allows an independent Finance Officer to approve a finance report', async () => { user = { ...user, role: Role.FINANCE_OFFICER }; prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, type: FormalReportType.FINANCE, status: FormalReportStatus.SUBMITTED, ownerId: otherId, submittedById: otherId }); const response = await (await login()).post(`/api/reports/reports/${reportId}/decision`).send({ approved: true, comment: 'Finance evidence verified' }); expect(response.status).toBe(200); expect(prismaMock.formalReport.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ reviewedById: userId }) })); });
  it('prevents report authors signing their own approved report', async () => { user = { ...user, role: Role.DEPARTMENT_HEAD }; prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.APPROVED, ownerId: userId }); const response = await (await login()).post(`/api/reports/reports/${reportId}/sign`); expect(response.status).toBe(403); });
  it('refuses signature when immutable content checksum fails', async () => { user = { ...user, role: Role.ADMINISTRATOR }; prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.APPROVED, ownerId: otherId, submittedById: otherId, versions: [{ ...version, checksum: '0'.repeat(64) }] }); const response = await (await login()).post(`/api/reports/reports/${reportId}/sign`); expect(response.status).toBe(409); });
  it('signs an approved integrity-verified report', async () => { user = { ...user, role: Role.ADMINISTRATOR }; prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.APPROVED, ownerId: otherId, submittedById: otherId, versions: [version] }); const response = await (await login()).post(`/api/reports/reports/${reportId}/sign`); expect(response.status).toBe(200); expect(prismaMock.formalReport.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ signedById: userId }) })); });
  it('requires signature before publication', async () => { user = { ...user, role: Role.ADMINISTRATOR }; prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.APPROVED }); const response = await (await login()).post(`/api/reports/reports/${reportId}/publish`); expect(response.status).toBe(409); });
  it('creates a new version rather than editing immutable report content', async () => { user = { ...user, role: Role.PROJECT_MANAGER }; const response = await (await login()).post(`/api/reports/reports/${reportId}/revise`).send(narrative); expect(response.status).toBe(200); expect(prismaMock.formalReportVersion.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ version: 2 }) })); });
  it('rejects insecure evidence links', async () => { user = { ...user, role: Role.PROJECT_MANAGER }; const response = await (await login()).post('/api/reports/evidence').send({ reportId, name: 'Evidence', url: 'http://files.example.com/evidence.pdf' }); expect(response.status).toBe(400); });
  it('rejects evidence versions belonging to another report', async () => { user = { ...user, role: Role.PROJECT_MANAGER }; prismaMock.formalReportVersion.findUnique.mockResolvedValue({ ...version, reportId: otherId }); const response = await (await login()).post('/api/reports/evidence').send({ reportId, versionId, name: 'Evidence', url: 'https://files.example.com/evidence.pdf' }); expect(response.status).toBe(400); });
  it('renders only approved integrity-verified formal output', async () => { prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.APPROVED, ownerId: otherId, reviewedBy: reportUser, versions: [version] }); const response = await (await login()).get(`/api/reports/reports/${reportId}/render.html`); expect(response.status).toBe(200); expect(response.headers['content-type']).toContain('text/html'); expect(response.text).toContain(digest); });
  it('exports a no-store formal evidence workbook source', async () => { prismaMock.formalReport.findUnique.mockResolvedValue({ ...formalReport, status: FormalReportStatus.SIGNED, ownerId: otherId, versions: [version] }); const response = await (await login()).get(`/api/reports/reports/${reportId}/export.csv`); expect(response.status).toBe(200); expect(response.headers['cache-control']).toContain('no-store'); expect(response.text).toContain('Projects in scope'); });
});
